name: Client CI

on:
  push:
    branches: [ main, PatrikoFeatures, MartynoFeatures, JulijosFeatures]
  pull_request:
    branches: [ main, PatrikoFeatures, MartynoFeatures, JulijosFeatures]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: housespotterinreact.client/package-lock.json
    - name: Install dependencies
      run: npm ci
      working-directory: housespotterinreact.client
    - name: Build
      run: npm run build --if-present
      working-directory: housespotterinreact.client
    - name: Test
      run: npm test
      working-directory: housespotterinreact.client
