name: Server CI

on:
  push:
    branches: [ main, PatrikoFeatures, JulijosFeatures]
  pull_request:
    branches: [ main, PatrikoFeatures, JulijosFeatures]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore Dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
